import bcrypt from "bcryptjs";

const data = {
	users: [
		{
			name: "Pushpendra",
			email: "pushpendraaa2.0@gmail.com",
			password: bcrypt.hashSync("Push@1996", 8),
			isAdmin: true,
			isSeller: true,
			seller: {
				name: "7Eleven",
				logo: "/images/logo1.png",
				description: "Best seller of the year.",
				rating: 4.5,
				numReviews: 120,
			},
		},
		{
			name: "Jhanvi",
			email: "jhanvii2.00@gmail.com",
			password: bcrypt.hashSync("Jhanvi@1996", 8),
			isAdmin: true,
			isSeller: true,
			seller: {
				name: "Jhanvi",
				logo: "/images/logo1.png",
				description: "Best seller of the month.",
				rating: 4,
				numReviews: 105,
			},
		},
		{
			name: "Bruce",
			email: "bruce@gmail.com",
			password: bcrypt.hashSync("bruce@1996", 8),
			isAdmin: false,
		},
		{
			name: "John",
			email: "john@gmail.com",
			password: bcrypt.hashSync("john@1996", 8),
			isAdmin: false,
		},
	],
	products: [
		{
			// _id: "1",
			name: "Slim Shirt",
			category: "Shirts",
			image: "/images/S01.webp",
			price: 99.99,
			brand: "Nike",
			rating: 5,
			numReviews: 10,
			countInStock: 15,
			description: "High quality product.",
		},
		{
			// _id: "2",
			name: "Fit Shirt",
			category: "Shirts",
			image: "/images/S03.webp",
			price: 70,
			brand: "Nike",
			rating: 4.5,
			numReviews: 10,
			countInStock: 7,
			description: "High quality product.",
		},
		{
			// _id: "3",
			name: "Best Shirt",
			category: "Shirts",
			image: "/images/S05.webp",
			price: 60,
			brand: "Nike",
			rating: 2.5,
			numReviews: 25,
			countInStock: 10,
			description: "High quality product.",
		},
		{
			// _id: "4",
			name: "Slim Pants",
			category: "Pants",
			image: "/images/p04.jpg",
			price: 100,
			brand: "Nike",
			rating: 4,
			numReviews: 10,
			countInStock: 0,
			description: "High quality product.",
		},
		{
			// _id: "5",
			name: "Fit Pants",
			category: "Pants",
			image: "/images/p05.jpg",
			price: 120,
			brand: "Nike",
			rating: 3.5,
			numReviews: 9,
			countInStock: 10,
			description: "High quality product.",
		},
		{
			// _id: "6",
			name: "Best Pants",
			category: "Pants",
			image: "/images/p06.jpg",
			price: 80,
			brand: "Nike",
			rating: 4.5,
			numReviews: 1,
			countInStock: 5,
			description: "High quality product.",
		},
	],
};

export default data;
