import bcrypt from "bcryptjs";
const data = {
	users: [
		{
			name: "Pushpendra",
			email: "pushpendraaa2.0@gmail.com",
			password: bcrypt.hashSync("1234", 8),
			isAdmin: true,
		},
		{
			name: "Bruce",
			email: "bruce@gmail.com",
			password: bcrypt.hashSync("1234", 8),
			isAdmin: false,
		},
	],
	products: [
		{
			// _id: "1",
			name: "Slim Shirt",
			category: "Shirts",
			image: "/images/S01.webp",
			price: 60,
			brand: "Nike",
			rating: 4.5,
			numReviews: 10,
			countInStock: 10,
			description: "High quality product.",
		},
		{
			// _id: "2",
			name: "Fit Shirt",
			category: "Shirts",
			image: "/images/S02.webp",
			price: 60,
			brand: "Nike",
			rating: 4.5,
			numReviews: 10,
			countInStock: 0,
			description: "High quality product.",
		},
		{
			// _id: "3",
			name: "Best Shirt",
			category: "Shirts",
			image: "/images/S03.webp",
			price: 60,
			brand: "Nike",
			rating: 4.5,
			numReviews: 10,
			countInStock: 10,
			description: "High quality product.",
		},
		{
			// _id: "4",
			name: "Slim Pants",
			category: "Pants",
			image: "/images/S04.webp",
			price: 60,
			brand: "Nike",
			rating: 4.5,
			numReviews: 10,
			countInStock: 0,
			description: "High quality product.",
		},
		{
			// _id: "5",
			name: "Fit Pants",
			category: "Pants",
			image: "/images/S05.webp",
			price: 60,
			brand: "Nike",
			rating: 4.5,
			numReviews: 10,
			countInStock: 10,
			description: "High quality product.",
		},
		{
			// _id: "6",
			name: "Best Pants",
			category: "Pants",
			image: "/images/S06.webp",
			price: 60,
			brand: "Nike",
			rating: 4.5,
			numReviews: 10,
			countInStock: 0,
			description: "High quality product.",
		},
	],
};

export default data;
