export const data = {
	products: [
		{
			_id: "1",
			name: "Slim Shirt",
			category: "Shirts",
			image: "/images/S01.webp",
			price: 60,
			brand: "Nike",
			rating: 4.5,
			numReviews: 10,
			countInStock: 10,
			description: "High quality product.",
		},
		{
			_id: "2",
			name: "Fit Shirt",
			category: "Shirts",
			image: "/images/S01.webp",
			price: 60,
			brand: "Nike",
			rating: 4.5,
			numReviews: 10,
			countInStock: 10,
			description: "High quality product.",
		},
		{
			_id: "3",
			name: "Best Shirt",
			category: "Shirts",
			image: "/images/S01.webp",
			price: 60,
			brand: "Nike",
			rating: 4.5,
			numReviews: 10,
			countInStock: 10,
			description: "High quality product.",
		},
		{
			_id: "4",
			name: "Slim Pants",
			category: "Pants",
			image: "/images/S01.webp",
			price: 60,
			brand: "Nike",
			rating: 4.5,
			numReviews: 10,
			countInStock: 10,
			description: "High quality product.",
		},
		{
			_id: "5",
			name: "Fit Pants",
			category: "Pants",
			image: "/images/S01.webp",
			price: 60,
			brand: "Nike",
			rating: 4.5,
			numReviews: 10,
			countInStock: 10,
			description: "High quality product.",
		},
		{
			_id: "6",
			name: "Best Pants",
			category: "Pants",
			image: "/images/S01.webp",
			price: 60,
			brand: "Nike",
			rating: 4.5,
			numReviews: 10,
			countInStock: 10,
			description: "High quality product.",
		},
	],
};
